### ISSUE TITLE
Cannot provide a value for property 'navBarLeftInjectableMenu'

### ISSUE THREAD

**Issue by ingermaa** [sjefvanleeuwen/blazor-adminlte#14]
Im getting this error while trying to setup a simple test project.

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'navBarLeftInjectableMenu' on type 'Test.Shared.MainLayout'. There is no registered service of type 'Blazor.AdminLte.NavBarLeftInjectableMenu'.
System.InvalidOperationException: Cannot provide a value for property 'navBarLeftInjectableMenu' on type 'Test.Shared.MainLayout'. There is no registered service of type 'Blazor.AdminLte.NavBarLeftInjectableMenu'.
  at Microsoft.AspNetCore.Components.ComponentFactory+<>c__DisplayClass5_0.<CreateInitializer>g__Initialize|2 (System.IServiceProvider serviceProvider, Microsoft.AspNetCore.Components.IComponent component) <0x2cb33f8 + 0x000e6> in <filename unknown>:0
```

I can see that the servicefactory is adding NavBarLeftInjectableMenu

`      services.AddScoped<NavBarLeftInjectableMenu>();
`

Im running a server and a client, should package Blazorized.AdminLte be referenced by both Client and Server?

**Comment by sjefvanleeuwen** [comment]
In the client and server, you register AdminLTE. i.e.: in WASM client:

https://github.com/sjefvanleeuwen/blazor-adminlte/blob/master/src/Blazor.AdminLte.Wasm/Program.cs
Line 17: builder.Services.AddAdminLte();

Within AddAdminLte the following services are registered for you:
https://github.com/sjefvanleeuwen/blazor-adminlte/blob/master/src/Blazor.AdminLte/ServiceCollectionExtensions.cs

Line:9: return services.AddScoped<NavBarLeftInjectableMenu>();

I have not Tested it with seperate client and server project combined and not sure what your project setup is. The project test WASM, or the Server version.

**Comment by ingermaa** [comment]
After more trobuleshooting i think i  found the cause of the error. 

For some strange reason builder.Services.AddAdminLte(); was not registred correctly. Maybe the cause was the order of adding services in the WASM client. It does not seem to be related to Blazor.AdminLte.
