### ISSUE TITLE
Add Link property to the SideBarUserPanel

### ISSUE THREAD

**Issue by vincejairam** [sjefvanleeuwen/blazor-adminlte#15]
Hi, can we add the Link property to the SideBarUserPanel component? I would like when the user clicks it to display their user details?

**Comment by sjefvanleeuwen** [comment]
Will probably do this this weekend.

**Comment by sjefvanleeuwen** [comment]
Implemented in commit https://github.com/sjefvanleeuwen/blazor-adminlte/commit/bd98b7cf4c084eaf176d47cf0c9c24919a6c526f
