### ISSUE TITLE
Add link property to the CarouselItem

### ISSUE THREAD

**Issue by vincejairam** [sjefvanleeuwen/blazor-adminlte#16]
Can we add a link property to the CarouselItem ?

**Comment by sjefvanleeuwen** [comment]
Will probably do this this weekend.

**Comment by sjefvanleeuwen** [comment]
Will probably do this this weekend.

**Comment by sjefvanleeuwen** [comment]
Implemented in Commit https://github.com/sjefvanleeuwen/blazor-adminlte/commit/33a912a26a01401876bb5cc03a1d0f1064766dcd
