### ISSUE TITLE
fixed sidebar with native scroll

### ISSUE THREAD

**Issue by pablokawan** [sjefvanleeuwen/blazor-adminlte#17]
its possible to set the layout to fixed sidebar with admin lte scrollbar ?

**Comment by sjefvanleeuwen** [comment]
Added in commits:

https://github.com/sjefvanleeuwen/blazor-adminlte/commit/e0617d0f716466277b94560415082193154f45b9
https://github.com/sjefvanleeuwen/blazor-adminlte/commit/ca06182a696ccd1f4476aebde15b9734bbb72e25

**Comment by sjefvanleeuwen** [comment]
Available in Release 0.1.0 https://github.com/sjefvanleeuwen/blazor-adminlte/releases/tag/0.1.0

https://www.nuget.org/packages/Blazorized.AdminLte/0.1.0

**Comment by pablokawan** [comment]
Dear sjefvanleeuwen, 
I meant, how to enable fixed sidebar with the adminlte 3.x scrollbar ? 
isn't a system sidebar uses (os-scrollbar)
https://adminlte.io/themes/v3/pages/layout/fixed-sidebar.html
