### ISSUE TITLE
Sidebar Menu Implement OS scrollbar

### ISSUE THREAD

**Issue by pablokawan** [sjefvanleeuwen/blazor-adminlte#18]
Dear sjefvanleeuwen,
I meant, how to enable fixed sidebar with the adminlte 3.x scrollbar ?
isn't a system scrollbar uses (os-scrollbar)
https://adminlte.io/themes/v3/pages/layout/fixed-sidebar.html

**Comment by sjefvanleeuwen** [comment]
OS Overlay for sidebar when fixed is enabled in commit: https://github.com/sjefvanleeuwen/blazor-adminlte/commit/a9edd61fa6790ee95ebc08301cded0bf443591d7

Please ignore the src/template commits as they accidentally where staged.

**Comment by sjefvanleeuwen** [comment]
released:
https://github.com/sjefvanleeuwen/blazor-adminlte/releases/tag/0.1.1
