### ISSUE TITLE
How do I set the SideBarMenuItem active menu on load

### ISSUE THREAD

**Issue by vincejairam** [sjefvanleeuwen/blazor-adminlte#19]
How do I set the active SideBarMenuItem ? e.g. when the app loads my default page is abc but I'm not sure how to set the menu item as active? This issue also occurs if you refresh the page on a specific route?

**Comment by sjefvanleeuwen** [comment]
This should be automatically handled by the sidebar menu item component. Marked this is a bug.

**Comment by sjefvanleeuwen** [comment]
Fixed in commimt: https://github.com/sjefvanleeuwen/blazor-adminlte/commit/420321e22d0161bbbac6800eb4a09dcd1d50a833

Scheduled to be in nuget release 0.1.1 soon

**Comment by sjefvanleeuwen** [comment]
released:
https://github.com/sjefvanleeuwen/blazor-adminlte/releases/tag/0.1.1
