### ISSUE TITLE
How to change SideBarTreeView to non active?

### ISSUE THREAD

**Issue by vincejairam** [sjefvanleeuwen/blazor-adminlte#21]
I have several SideBarMenuItem and they are shown active "Blue" when I click on each item. Now I have a SideBarTreeView and it's menu state is set to open but the color of the item looks active too "Blue" now when I click on one of the sub items under the SideBarTreeView the color of the sub items are gray not "Blue". 

Can I change the SideBarTreeView  color to gray and its sub items to "Blue" when they are active? This seems more consistent with selected menu items?

**Comment by sjefvanleeuwen** [comment]
The original ADMINLTE starter pages do the same. I Suppose it should be handled by a CSS file. In the newer .NET we have isolated CSS/SASS. otherwise use site.css ?

**Comment by sjefvanleeuwen** [comment]
Extended to issue: #24
