### ISSUE TITLE
side panel doesn't close in mobile mode in Blazor Server

### ISSUE THREAD

**Issue by taalaibekgh** [sjefvanleeuwen/blazor-adminlte#23]
side panel doesn't close in mobile mode in Blazor Server.
How can we fix

**Comment by taalaibekgh** [comment]
![Capture](https://user-images.githubusercontent.com/18408272/97402549-e8c5fc00-191c-11eb-95d6-323d87cd8da7.PNG)


And is not minimized in desktop mode, hides completely

**Comment by sjefvanleeuwen** [comment]
Which mobile device and browser type are you using?

**Comment by taalaibekgh** [comment]
[bug video.zip](https://github.com/sjefvanleeuwen/blazor-adminlte/files/5455956/bug.video.zip)
this is short video, you can try self  http://etest.line.kg
Mobile device is XIAOMI 6A, browser Edge and Chrome, both last version

**Comment by taalaibekgh** [comment]
Problem solved! I forgot change class of body in _Host.cshtml file.
I change 
<body>
    <app>
      ....
    </app>

to

<body class="hold-transition sidebar-mini sidebar-collapse">
    <div class="wrapper">
        <app> ......
