### ISSUE TITLE
NavBarLeftInjectableMenu Issue

### ISSUE THREAD

**Issue by slynch401k** [sjefvanleeuwen/blazor-adminlte#26]
I am a beginner, when following your directions nothing renders with adminlte. I installed both nuget packages and nothing. Then I then added services.AddAdminLte(); to Startup.cs and copied your MainLayout and Host into mine changing the namespaces.

I get an error not finding @inject NavBarLeftInjectableMenu navBarLeftInjectableMenu.

Can you post a standalone server solution only? or show me how to code the class for injecting navbarleft?  Believe me I tried but after 3 hours I am done.

**Comment by sjefvanleeuwen** [comment]
You can find a server only template project in https://github.com/sjefvanleeuwen/blazor-adminlte/tree/master/src/Templates
Note that you need .NET5 and Visual Studio 2019 Preview (at least the 16.8 release).
https://visualstudio.microsoft.com/vs/preview/

**Comment by slynch401k** [comment]
Thank you.
