### ISSUE TITLE
Clicking side bar menu item does not automatically collapse the side bar.

### ISSUE THREAD

**Issue by alanmachadouk** [sjefvanleeuwen/blazor-adminlte#34]
Great job in the conversion, just testing and found this annoying difference.

When the side bar is in a collapsed state.

![image](https://user-images.githubusercontent.com/24925692/100118465-c963b580-2e6d-11eb-8030-6a47a8374063.png)

Clicking SideBarMenuItem menu item does not automatically collapse.
It is left for the user to move move away from side bar before the collapse occurs.

![image](https://user-images.githubusercontent.com/24925692/100118746-0af46080-2e6e-11eb-9e07-abd7f5b73297.png)

This is different behavior to AdminLTE.

**Comment by sjefvanleeuwen** [comment]
Confgirmed.
