### ISSUE TITLE
Sidebar problem in Blazor (webassembly)

### ISSUE THREAD

**Issue by matteoventuri7** [sjefvanleeuwen/blazor-adminlte#35]
Hi, i noticed that in my blazor webassembly project (.Net 5.0) the sidebar fully disappear on every page change even if I open it.

**Comment by sjefvanleeuwen** [comment]
This behavior is not reproducable here. Without more information i can't determine if this is a false negative. It should work.
Can you share code of the MainLayout, and check if there's no javascript errors etc. ?

**Comment by matteoventuri7** [comment]
Sure.
MainLayout: https://pastebin.com/qDJtw915
Image homepage not logged in: https://ibb.co/GFwvXsV
Image homepage logged in: https://ibb.co/dBngdn3

**Comment by sjefvanleeuwen** [comment]
Can't reproduce it here. Does the problem still exist when you take the <Authorize> tags off?
