### ISSUE TITLE
NavBarLeftInjectableMenu Tutorial

### ISSUE THREAD

**Issue by hussamelvani** [sjefvanleeuwen/blazor-adminlte#37]
Hello,

Would you please point me to an example which uses this?
Or could you please explain how it should be used? I don't seem to be able to make it work.

Thanks in advance.

Regards.

**Comment by sjefvanleeuwen** [comment]
Hello,

I have made a quick tutorial.
https://github.com/sjefvanleeuwen/blazor-adminlte/blob/master/docs/navbar-left-injectable-menu.md

Let me know if that works for you.

Regards.

**Comment by hussamelvani** [comment]
Helped me a lot! Thanks for the detailed explanation.
