### ISSUE TITLE
Sidebar remains open after click on mobile

### ISSUE THREAD

**Issue by djordjedjukic** [sjefvanleeuwen/blazor-adminlte#38]
When you open some item from sidemenu on mobile, after click on menu item, menu remains open, and you must click somewhere to close it. It would be more user friendly if sidemenu close after click? 
Do you maybe have some solution for this?
Thanks

**Comment by sjefvanleeuwen** [comment]
This shoul have been fixed in release: https://github.com/sjefvanleeuwen/blazor-adminlte/releases/tag/0.1.6
specifically change: https://github.com/sjefvanleeuwen/blazor-adminlte/commit/840fe7d8c8f0fe82d6804cc3e3d70ebd691391f6

please confirm.
