### ISSUE TITLE
Failed to find a valid digest

### ISSUE THREAD

**Issue by Lima-Roberto** [sjefvanleeuwen/blazor-adminlte#40]
Hi guys,

I'm having a problem only when I publish my app (details below), I think that this is stopping me to "install" the app using PWA, the weird thing is that on my local machine all works fine.

Could you please have any clue that might help me solve the issue?

Failed to find a valid digest in the 'integrity' attribute for resource 'https://***/BlazorWMS/_content/Blazorized.AdminLte.Content/plugins/raphael/.eslintrc.js' with computed SHA-256 integrity '47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='. The resource has been blocked.
Unknown error occurred while trying to verify integrity.
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch

Thanks.

**Comment by Lima-Roberto** [comment]
I problably found the reason of the failure, it's beacuse my browser returns http code 404 oh this particule js, maybe this is beacause the name starts with "."

I tried to load several files and all loading fine, except this
http://localhost:81/_content/Blazorized.AdminLte.Content/plugins/raphael/.eslintrc.js

Can you please change the name of this js (.eslintrc.js) and push an update?

Bellow the microsoft docs excerpt show what I'm talking 

Diagnosing integrity problems
When an app is built, the generated blazor.boot.json manifest describes the SHA-256 hashes of your boot resources (for example, .dll, .wasm, and other files) at the time that the build output is produced. The integrity check passes as long as the SHA-256 hashes in blazor.boot.json match the files delivered to the browser.

Common reasons why this fails are:

The web server's response is an error (for example, a 404 - Not Found or a 500 - Internal Server Error) instead of the file the browser requested. This is reported by the browser as an integrity check failure and not as a response failure.

URL of the microsoft doc
https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#resolve-integrity-check-failures

**Comment by sjefvanleeuwen** [comment]
Publishing seems to work fine here. Not sure what your method of publishing is. In this case I have used to web publishing tool built into dot net.

The resulting demo website: https://blazorize-adminlte.morstead.nl/ is running wasm. This is the output and does not show integrity issues. Maybe you are publishing too many files than that are actually referenced. .eslintrc.js is a configuration file during development and should not be published.

![image](https://user-images.githubusercontent.com/36629650/104739433-fe420980-5746-11eb-981e-b4d23aa7dca9.png)

**Comment by sjefvanleeuwen** [comment]
This is the blazor boot.json behing the hosted one for your verification:
https://github.com/sjefvanleeuwen/blazor-adminlte/blob/gh-pages/_framework/blazor.boot.json

**Comment by Lima-Roberto** [comment]
Thanks for the answer, I'll try to start a new projetct and see if the error persists.
I am publishing on VS 19.

**Comment by sjefvanleeuwen** [comment]
Raphael has been cleanup in commit 8ab248af7d411f8ee90a76456e162d27201387ee

nuget availabe at: https://www.nuget.org/packages/Blazorized.AdminLte.Content/3.0.6

**Comment by sjefvanleeuwen** [comment]
Please reopen this issue, if the problem continues to exist.
