### ISSUE TITLE
Issue with the nuget package

### ISSUE THREAD

**Issue by jerpic** [sjefvanleeuwen/blazor-adminlte#43]
Hello,

Thanks for your work.

I would like to use your project but unfortunately after adding the nuget "Blazorized.AdminLte 0.1.8" the line services.AddAdminLte() is not recognized, ILayoutManager and NavBarLeftInjectableMenu as well.

Could you help me please?

Best Regards,

**Comment by sjefvanleeuwen** [comment]
Did you add "using Blazor.AdminLte" in your Startup.cs ?

**Comment by jerpic** [comment]
Hi @sjefvanleeuwen,

Thanks for your reply. 

As you can see in the image, the Blazor package is not recognized even though the nuget Blazorized.AdminLte is properly installed.

Does I missed something?

Best Regards,
Jérôme.

![image](https://user-images.githubusercontent.com/8591455/105906793-700e3300-6024-11eb-84c5-7acbd621c59c.png)

**Comment by sjefvanleeuwen** [comment]
Please update nuget to 1.0.8 let me know

**Comment by jerpic** [comment]
Hi @sjefvanleeuwen,

Many thanks for you recommandations, after upgrading to .net 5.0 and 1.0.8 for Blazorized.AdminLite everything is now recoggnized and I can execute the webapp.

But, I have another issue, the render is not what it should be, do I have to add manually some css and images?

Best Regards,
Jérôme.

![image](https://user-images.githubusercontent.com/8591455/105976813-e8124280-6090-11eb-83ba-5fd366bf2b5d.png)

**Comment by jerpic** [comment]
Sorry, I have found my mistake regarding the render.

You close that tissue.

Thanks again for your help!

**Comment by jerpic** [comment]
Sorry, I have found my mistake regarding the render.

You close that tissue.

Thanks again for your help!
