### ISSUE TITLE
Setting only Width or Size or neither should render OK

### ISSUE THREAD

**Issue by jbennink** [sjefvanleeuwen/blazor-adminlte#7]
Also found an issue when setting only the Width. In Bootstrap you can set `col-xs-6` or `col-6` and the two mean the same. We might want to fix that as no only supplying Width give `col--6` and not supplying both give `col--` which are both not rendered correctly.

_Originally posted by @jbennink in https://github.com/sjefvanleeuwen/blazor-adminlte/issues/6#issuecomment-674084370_

**Comment by sjefvanleeuwen** [comment]
Linked To Issue: https://github.com/sjefvanleeuwen/blazor-adminlte/issues/6
Implementing that enhancement instead.
