### ISSUE TITLE
Support custom tools in CardTools component

### ISSUE THREAD

**Issue by jbennink** [sjefvanleeuwen/blazor-adminlte#9]
As seen in the AdminLte template on the widgets page the Chart widget uses a card and places chat specific buttons. Also for my own use I use a card to hold a result list that can be changed with a date picker that I placed the `card-tools` area.
The `card-tools` area should be open to more that the standard options shown in the default Cards example

**Comment by sjefvanleeuwen** [comment]
See Commit RenderFragment for Custom Card Tools https://github.com/sjefvanleeuwen/blazor-adminlte/commit/41445f5e0fff4a9a0a95eabd017bfdbe77ca5944
